name: BoneMeal4Mobs
main: io.github.Skepter.Main
version: [1.5]
author: Skepter
description: Bonemeal mobs to create larger ones!

permissions:
   BoneMeal4Mobs.*:
     description: Gives access to all antibonemeal.
     children:
       BoneMeal4Mobs.zombie: true
       BoneMeal4Mobs.cow: true
       BoneMeal4Mobs.sheep: true
       BoneMeal4Mobs.chicken: true
       BoneMeal4Mobs.pig: true
       BoneMeal4Mobs.villager: true
       BoneMeal4Mobs.wolf: true
       BoneMeal4Mobs.ocelot: true
       BoneMeal4Mobs.mooshroom: true
       BoneMeal4Mobs.slime: true
       BoneMeal4Mobs.magmacube: true
       BoneMeal4Mobs.spider: true
       BoneMeal4Mobs.horse: true
       BoneMeal4Mobs.zombiepigman: true
       BoneMeal4Mobs.skeleton: true
       BoneMeal4Mobs.antizombie: true
       BoneMeal4Mobs.anticow: true
       BoneMeal4Mobs.antisheep: true
       BoneMeal4Mobs.antichicken: true
       BoneMeal4Mobs.antipig: true
       BoneMeal4Mobs.antivillager: true
       BoneMeal4Mobs.antiwolf: true
       BoneMeal4Mobs.antiocelot: true
       BoneMeal4Mobs.antimooshroom: true
       BoneMeal4Mobs.antislime: true
       BoneMeal4Mobs.antimagmacube: true
       BoneMeal4Mobs.antispider: true
       BoneMeal4Mobs.antihorse: true
       BoneMeal4Mobs.antizombiepigman: true
       BoneMeal4Mobs.antiskeleton: true   
   BoneMeal4Mobs.zombie:
     description: Allows you to antibonemeal zombies
     default: true
   BoneMeal4Mobs.cow:
     description: Allows you to antibonemeal cows
     default: true
   BoneMeal4Mobs.sheep:
     description: Allows you to antibonemeal sheep
     default: true
   BoneMeal4Mobs.chicken:
     description: Allows you to antibonemeal chickens
     default: true
   BoneMeal4Mobs.pig:
     description: Allows you to antibonemeal pigs
     default: true
   BoneMeal4Mobs.villager:
     description: Allows you to antibonemeal villagers
     default: true
   BoneMeal4Mobs.wolf:
     description: Allows you to antibonemeal wolves
     default: true
   BoneMeal4Mobs.ocelot:
     description: Allows you to antibonemeal ocelots
     default: true
   BoneMeal4Mobs.mooshroom:
     description: Allows you to antibonemeal mooshrooms
     default: true
   BoneMeal4Mobs.slime:
     description: Allows you to antibonemeal slimes
     default: true
   BoneMeal4Mobs.magmacube:
     description: Allows you to antibonemeal magma cubes
     default: true
   BoneMeal4Mobs.spider:
     description: Allows you to antibonemeal cave spiders
     default: true
   BoneMeal4Mobs.horse:
     description: Allows you to antibonemeal horses
     default: true  
   BoneMeal4Mobs.zombiepigman:
     description: Allows you to antibonemeal zombiepigmen
     default: true
   BoneMeal4Mobs.skeleton:
     description: Allows you to antibonemeal skeletons
     default: true
   BoneMeal4Mobs.antizombie:
     description: Allows you to antibonemeal zombies and giants
     default: true
   BoneMeal4Mobs.anticow:
     description: Allows you to antibonemeal cows
     default: true
   BoneMeal4Mobs.antisheep:
     description: Allows you to antibonemeal sheep
     default: true
   BoneMeal4Mobs.antichicken:
     description: Allows you to antibonemeal chickens
     default: true
   BoneMeal4Mobs.antipig:
     description: Allows you to antibonemeal pigs
     default: true
   BoneMeal4Mobs.antivillager:
     description: Allows you to antibonemeal villagers
     default: true
   BoneMeal4Mobs.antiwolf:
     description: Allows you to antibonemeal wolves
     default: true
   BoneMeal4Mobs.antiocelot:
     description: Allows you to antibonemeal ocelots
     default: true
   BoneMeal4Mobs.antimooshroom:
     description: Allows you to antibonemeal mooshrooms
     default: true
   BoneMeal4Mobs.antislime:
     description: Allows you to antibonemeal slimes
     default: true
   BoneMeal4Mobs.antimagmacube:
     description: Allows you to antibonemeal magma cubes
     default: true
   BoneMeal4Mobs.antispider:
     description: Allows you to antibonemeal spiders
     default: true
   BoneMeal4Mobs.antihorse:
     description: Allows you to antibonemeal horses
     default: true  
   BoneMeal4Mobs.antizombiepigman:
     description: Allows you to antibonemeal zombiepigmen
     default: true
   BoneMeal4Mobs.antiskeleton:
     description: Allows you to antibonemeal wither skeletons
     default: true